<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\UCA.xaml.cs" />
    <Compile Remove="Views\UCB.xaml.cs" />
    <Compile Remove="Views\UCC.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Modules\ModuleA.dll" />
    <None Remove="Modules\ModuleB.dll" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Views\UCA.xaml" />
    <Page Remove="Views\UCB.xaml" />
    <Page Remove="Views\UCC.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Modules\ModuleA.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Modules\ModuleB.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
